const GET_MATCHES = 'GET_MATCHES';
const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
const GET_MATCHES_FAILURE = 'GET_MATCHES_FAILURE';

const ADD_MATCH = 'ADD_MATCH';
const ADD_MATCH_SUCCESS = 'ADD_MATCH_SUCCESS';
const ADD_MATCH_FAILURE = 'ADD_MATCH_FAILURE';

